/**
 * Universal Minting Service
 * 
 * Mints tokens from ANY contract generated by the Smart Contract Generator
 * Handles all Solana complexity: IDL fetching, PDA derivation, ATA creation, etc.
 */

import { 
  Connection, 
  PublicKey, 
  Transaction,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
  TransactionInstruction,
  Keypair,
  sendAndConfirmTransaction
} from '@solana/web3.js';
import { 
  Program, 
  AnchorProvider, 
  web3, 
  BN,
  Idl,
  Wallet
} from '@coral-xyz/anchor';
import { 
  TOKEN_PROGRAM_ID, 
  ASSOCIATED_TOKEN_PROGRAM_ID,
  getAssociatedTokenAddress,
  createAssociatedTokenAccountInstruction,
  getMint,
  getAccount as getTokenAccount
} from '@solana/spl-token';

export type MintConfig = {
  contractAddress: string;
  recipientAddress: string;
  amount: number;
  rpcUrl?: string;
  wallet?: any;
};

export type MintResult = {
  signature: string;
  tokenAccount: string;
  mintAuthority: string;
  totalMinted: number;
  explorerUrl: string;
};

export type MintProgress = {
  step: 'connecting' | 'fetching-idl' | 'deriving-accounts' | 'creating-ata' | 'minting' | 'confirming' | 'complete';
  message: string;
};

/**
 * Universal Minting Service Class
 */
export class UniversalMintingService {
  private connection: Connection;
  private provider?: AnchorProvider;
  private onProgress?: (progress: MintProgress) => void;

  constructor(
    rpcUrl: string = 'https://api.devnet.solana.com',
    wallet?: any,
    onProgress?: (progress: MintProgress) => void
  ) {
    this.connection = new Connection(rpcUrl, 'confirmed');
    this.onProgress = onProgress;
    
    if (wallet) {
      this.provider = new AnchorProvider(
        this.connection,
        wallet as Wallet,
        { commitment: 'confirmed', preflightCommitment: 'confirmed' }
      );
    }
  }

  private log(step: MintProgress['step'], message: string) {
    console.log(`[${step}] ${message}`);
    this.onProgress?.({ step, message });
  }

  /**
   * Fetch IDL for a deployed contract
   * Tries multiple methods to get the IDL
   */
  async fetchContractIdl(programId: PublicKey): Promise<Idl | null> {
    this.log('fetching-idl', 'Fetching contract IDL...');
    
    // Method 1: Try Anchor's on-chain IDL account
    try {
      if (this.provider) {
        const idl = await Program.fetchIdl(programId, this.provider);
        if (idl) {
          console.log('✅ IDL fetched from on-chain Anchor account');
          return idl;
        }
      }
    } catch (error) {
      console.warn('⚠️ Could not fetch on-chain IDL:', error);
    }
    
    // Method 2: Try to fetch from Smart Contract Generator API
    try {
      const response = await fetch(
        `http://localhost:5000/api/v1/contracts/idl/${programId.toBase58()}`
      );
      
      if (response.ok) {
        const idl = await response.json();
        console.log('✅ IDL fetched from Smart Contract Generator API');
        return idl;
      }
    } catch (error) {
      console.warn('⚠️ Could not fetch IDL from API:', error);
    }
    
    // Method 3: Try common storage locations
    // (Could expand this to check IPFS, Arweave, etc.)
    
    throw new Error(
      'Could not fetch contract IDL. ' +
      'Please ensure the contract was deployed with IDL storage enabled.'
    );
  }

  /**
   * Derive standard PDAs used by generated contracts
   */
  async deriveStandardAccounts(programId: PublicKey): Promise<{
    mintAuthority: PublicKey;
    mintAuthorityBump: number;
    propertyPda: PublicKey;
    propertyBump: number;
  }> {
    this.log('deriving-accounts', 'Deriving program accounts...');
    
    // Standard mint authority PDA (all contracts use this seed)
    const [mintAuthority, mintAuthorityBump] = await PublicKey.findProgramAddress(
      [Buffer.from('mint-authority')],
      programId
    );
    
    // Standard property data PDA
    const [propertyPda, propertyBump] = await PublicKey.findProgramAddress(
      [Buffer.from('property')],
      programId
    );
    
    console.log('🔑 Mint Authority:', mintAuthority.toBase58());
    console.log('🏠 Property PDA:', propertyPda.toBase58());
    
    return {
      mintAuthority,
      mintAuthorityBump,
      propertyPda,
      propertyBump
    };
  }

  /**
   * Main minting function - works with ANY generated contract
   */
  async mintTokens(config: MintConfig): Promise<MintResult> {
    if (!this.provider) {
      throw new Error('Wallet not connected. Please connect a Solana wallet.');
    }

    this.log('connecting', 'Connecting to Solana network...');
    console.log('🚀 Universal Minting Service started');
    console.log('📍 Contract:', config.contractAddress);
    console.log('👤 Recipient:', config.recipientAddress);
    console.log('💰 Amount:', config.amount);
    
    const programId = new PublicKey(config.contractAddress);
    const recipient = new PublicKey(config.recipientAddress);
    
    // Step 1: Fetch contract IDL
    const idl = await this.fetchContractIdl(programId);
    if (!idl) {
      throw new Error('Failed to fetch contract IDL');
    }
    
    const program = new Program(idl, programId, this.provider);
    console.log('✅ Program initialized');
    
    // Step 2: Derive standard accounts
    const accounts = await this.deriveStandardAccounts(programId);
    
    // Step 3: Get property account data
    this.log('fetching-idl', 'Fetching property data...');
    const propertyAccount = await program.account.property.fetch(accounts.propertyPda);
    const mintPubkey = propertyAccount.mint as PublicKey;
    
    console.log('🪙 Mint:', mintPubkey.toBase58());
    console.log('📊 Total Supply:', (propertyAccount.totalSupply as BN).toString());
    console.log('📊 Total Minted:', (propertyAccount.totalMinted as BN).toString());
    
    // Step 4: Get or create recipient's associated token account
    this.log('creating-ata', 'Setting up recipient token account...');
    const recipientTokenAccount = await getAssociatedTokenAddress(
      mintPubkey,
      recipient
    );
    
    console.log('💳 Recipient Token Account:', recipientTokenAccount.toBase58());
    
    // Check if account exists
    let needsAta = false;
    try {
      await getTokenAccount(this.connection, recipientTokenAccount);
      console.log('✅ Token account already exists');
    } catch {
      console.log('📝 Token account needs to be created');
      needsAta = true;
    }
    
    // Step 5: Build transaction
    this.log('minting', 'Building mint transaction...');
    const tx = new Transaction();
    
    // Add create ATA instruction if needed
    if (needsAta) {
      tx.add(
        createAssociatedTokenAccountInstruction(
          this.provider.wallet.publicKey,
          recipientTokenAccount,
          recipient,
          mintPubkey,
          TOKEN_PROGRAM_ID,
          ASSOCIATED_TOKEN_PROGRAM_ID
        )
      );
      console.log('➕ Added create ATA instruction');
    }
    
    // Add mint instruction (calls YOUR contract's mint_tokens function)
    const mintIx = await program.methods
      .mintTokens(new BN(config.amount))
      .accounts({
        property: accounts.propertyPda,
        mint: mintPubkey,
        recipientTokenAccount: recipientTokenAccount,
        recipient: recipient,
        mintAuthority: accounts.mintAuthority,
        authority: this.provider.wallet.publicKey,
        tokenProgram: TOKEN_PROGRAM_ID,
        associatedTokenProgram: ASSOCIATED_TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .instruction();
    
    tx.add(mintIx);
    console.log('➕ Added mint instruction');
    
    // Step 6: Send and confirm transaction
    this.log('confirming', 'Sending transaction to Solana...');
    const signature = await this.provider.sendAndConfirm(tx, [], {
      commitment: 'confirmed',
      preflightCommitment: 'confirmed'
    });
    
    console.log('✅ Transaction confirmed!');
    console.log('🔗 Signature:', signature);
    
    // Step 7: Build explorer URL
    const cluster = config.rpcUrl?.includes('devnet') ? 'devnet' :
                    config.rpcUrl?.includes('testnet') ? 'testnet' : 'mainnet-beta';
    const explorerUrl = `https://explorer.solana.com/tx/${signature}?cluster=${cluster}`;
    
    this.log('complete', 'Minting complete!');
    
    return {
      signature,
      tokenAccount: recipientTokenAccount.toBase58(),
      mintAuthority: accounts.mintAuthority.toBase58(),
      totalMinted: config.amount,
      explorerUrl
    };
  }

  /**
   * Get current minting status from contract
   */
  async getMintingStatus(contractAddress: string): Promise<{
    totalSupply: number;
    totalMinted: number;
    remaining: number;
    mintAddress: string;
    mintAuthority: string;
  }> {
    if (!this.provider) {
      throw new Error('Provider not initialized');
    }

    const programId = new PublicKey(contractAddress);
    const idl = await this.fetchContractIdl(programId);
    
    if (!idl) {
      throw new Error('Could not fetch IDL');
    }
    
    const program = new Program(idl, programId, this.provider);
    const accounts = await this.deriveStandardAccounts(programId);
    
    const propertyAccount = await program.account.property.fetch(accounts.propertyPda);
    
    const totalSupply = (propertyAccount.totalSupply as BN).toNumber();
    const totalMinted = (propertyAccount.totalMinted as BN).toNumber();
    
    return {
      totalSupply,
      totalMinted,
      remaining: totalSupply - totalMinted,
      mintAddress: (propertyAccount.mint as PublicKey).toBase58(),
      mintAuthority: accounts.mintAuthority.toBase58()
    };
  }

  /**
   * Batch mint to multiple recipients
   */
  async batchMint(
    contractAddress: string,
    recipients: Array<{ address: string; amount: number }>
  ): Promise<MintResult[]> {
    console.log(`🎯 Batch minting to ${recipients.length} recipients...`);
    
    const results: MintResult[] = [];
    
    for (const [index, recipient] of recipients.entries()) {
      console.log(`\n[${index + 1}/${recipients.length}] Minting to ${recipient.address}...`);
      
      const result = await this.mintTokens({
        contractAddress,
        recipientAddress: recipient.address,
        amount: recipient.amount
      });
      
      results.push(result);
      console.log(`✅ Batch ${index + 1} complete`);
    }
    
    console.log(`\n🎉 Batch minting complete! ${results.length} transactions confirmed.`);
    return results;
  }
}

/**
 * Simplified wrapper for wizard integration
 * Automatically connects to browser wallet (Phantom, Solflare, etc.)
 */
export async function mintFromContract(
  contractAddress: string,
  recipientAddress: string,
  amount: number,
  rpcUrl: string = 'https://api.devnet.solana.com',
  onProgress?: (progress: MintProgress) => void
): Promise<MintResult> {
  // Check for browser wallet
  const wallet = (window as any).solana;
  
  if (!wallet) {
    throw new Error(
      'No Solana wallet detected. Please install Phantom (https://phantom.app) or Solflare (https://solflare.com)'
    );
  }
  
  // Connect wallet if not already connected
  if (!wallet.isConnected) {
    console.log('👛 Connecting to wallet...');
    await wallet.connect();
  }
  
  console.log('✅ Wallet connected:', wallet.publicKey.toBase58());
  
  // Create service and mint
  const service = new UniversalMintingService(rpcUrl, wallet, onProgress);
  
  return await service.mintTokens({
    contractAddress,
    recipientAddress: recipientAddress || wallet.publicKey.toBase58(),
    amount
  });
}

/**
 * Get wallet address from browser
 */
export async function getWalletAddress(): Promise<string> {
  const wallet = (window as any).solana;
  
  if (!wallet) {
    throw new Error('No Solana wallet detected');
  }
  
  if (!wallet.isConnected) {
    await wallet.connect();
  }
  
  return wallet.publicKey.toBase58();
}

/**
 * Check if wallet is connected
 */
export function isWalletConnected(): boolean {
  const wallet = (window as any).solana;
  return wallet?.isConnected ?? false;
}

/**
 * Disconnect wallet
 */
export async function disconnectWallet(): Promise<void> {
  const wallet = (window as any).solana;
  if (wallet?.isConnected) {
    await wallet.disconnect();
  }
}

/**
 * Batch mint helper
 */
export async function batchMintFromContract(
  contractAddress: string,
  recipients: Array<{ address: string; amount: number }>,
  rpcUrl: string = 'https://api.devnet.solana.com',
  onProgress?: (progress: MintProgress) => void
): Promise<MintResult[]> {
  const wallet = (window as any).solana;
  
  if (!wallet) {
    throw new Error('No Solana wallet detected');
  }
  
  if (!wallet.isConnected) {
    await wallet.connect();
  }
  
  const service = new UniversalMintingService(rpcUrl, wallet, onProgress);
  return await service.batchMint(contractAddress, recipients);
}

/**
 * Get minting status for a contract
 */
export async function getContractMintStatus(
  contractAddress: string,
  rpcUrl: string = 'https://api.devnet.solana.com'
): Promise<{
  totalSupply: number;
  totalMinted: number;
  remaining: number;
  percentMinted: number;
}> {
  const wallet = (window as any).solana;
  
  if (!wallet) {
    throw new Error('No Solana wallet detected');
  }
  
  const service = new UniversalMintingService(rpcUrl, wallet);
  const status = await service.getMintingStatus(contractAddress);
  
  return {
    ...status,
    percentMinted: Math.round((status.totalMinted / status.totalSupply) * 100)
  };
}


